
{{ if .Values.CREATE_NEW_IMAGE_STREAM }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{ default .Release.Name .Values.NAME_OVERRIDE }}
  name: repo
spec:
  lookupPolicy:
    local: true
{{ end }}